### ISSUE TITLE
AD0001

### ISSUE THREAD

**Issue by JohanLarsson** [GuOrg/Gu.Analyzers#260]
```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	AD0001	Analyzer 'Gu.Analyzers.GU0023StaticMemberOrderAnalyzer' threw an exception of type 'System.ArgumentNullException' with message 'Value cannot be null.
Parameter name: node'.	Gu.Wpf.NumericInput.UiTests		1	Active	Analyzer 'Gu.Analyzers.GU0023StaticMemberOrderAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: Gu.Wpf.NumericInput.UiTests
SyntaxTree: C:\Git\_GuOrg\Gu.Wpf.NumericInput\Gu.Wpf.NumericInput.UITests\DoubleBox\FocusWindowTests.cs
SyntaxNode: private const string WindowName ... [FieldDeclarationSyntax]@[165..213) (7,8)-(7,56)

System.ArgumentNullException: Value cannot be null.
Parameter name: node
   at Gu.Roslyn.AnalyzerExtensions.SemanticModelExt.GetDeclaredSymbolSafe(SemanticModel semanticModel, TypeDeclarationSyntax node, CancellationToken cancellationToken)
   at Gu.Roslyn.AnalyzerExtensions.Recursion.Borrow(SyntaxNode startLocation, SemanticModel semanticModel, CancellationToken cancellationToken)
   at Gu.Roslyn.AnalyzerExtensions.ExecutionWalker`1.BorrowAndVisit(SyntaxNode node, SearchScope scope, SemanticModel semanticModel, CancellationToken cancellationToken, Func`1 create)
   at Gu.Analyzers.GU0023StaticMemberOrderAnalyzer.Walker.Borrow(SyntaxNode node, SemanticModel semanticModel, CancellationToken cancellationToken)
   at Gu.Analyzers.GU0023StaticMemberOrderAnalyzer.IsInitializedWithUninitialized(MemberDeclarationSyntax member, ExpressionSyntax value, SyntaxNodeAnalysisContext context, FieldOrProperty& other)
   at Gu.Analyzers.GU0023StaticMemberOrderAnalyzer.Handle(SyntaxNodeAnalysisContext context)
   at Gu.Analyzers.GU0023StaticMemberOrderAnalyzer.<>c.<Initialize>b__3_0(SyntaxNodeAnalysisContext c)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__53`1.<ExecuteSyntaxNodeAction>b__53_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.
```

**Comment by JohanLarsson** [comment]
```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	AD0001	Analyzer 'Gu.Analyzers.SimpleAssignmentAnalyzer' threw an exception of type 'System.ArgumentNullException' with message 'Value cannot be null.
Parameter name: node'.	Gu.Wpf.NumericInput.UiTests		1	Active	Analyzer 'Gu.Analyzers.SimpleAssignmentAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: Gu.Wpf.NumericInput.UiTests
SyntaxTree: C:\Git\_GuOrg\Gu.Wpf.NumericInput\Gu.Wpf.NumericInput.UITests\DoubleBox\FocusWindowTests.cs
SyntaxNode: window.FindCheckBox("AllowSpinners" ... [AssignmentExpressionSyntax]@[546..600) (16,12)-(16,66)

System.ArgumentNullException: Value cannot be null.
Parameter name: node
   at Gu.Roslyn.AnalyzerExtensions.SemanticModelExt.GetDeclaredSymbolSafe(SemanticModel semanticModel, TypeDeclarationSyntax node, CancellationToken cancellationToken)
   at Gu.Roslyn.AnalyzerExtensions.Recursion.Borrow(SyntaxNode startLocation, SemanticModel semanticModel, CancellationToken cancellationToken)
   at Gu.Roslyn.AnalyzerExtensions.ExecutionWalker`1.BorrowAndVisit(SyntaxNode node, SearchScope scope, SemanticModel semanticModel, CancellationToken cancellationToken, Func`1 create)
   at Gu.Roslyn.AnalyzerExtensions.AssignmentExecutionWalker.Borrow(SyntaxNode node, SearchScope scope, SemanticModel semanticModel, CancellationToken cancellationToken)
   at Gu.Roslyn.AnalyzerExtensions.AssignmentExecutionWalker.For(ISymbol symbol, SyntaxNode node, SearchScope scope, SemanticModel semanticModel, CancellationToken cancellationToken)
   at Gu.Analyzers.SimpleAssignmentAnalyzer.IsRedundantAssignment(ISymbol left, AssignmentExpressionSyntax assignment, SyntaxNodeAnalysisContext context)
   at Gu.Analyzers.SimpleAssignmentAnalyzer.Handle(SyntaxNodeAnalysisContext context)
   at Gu.Analyzers.SimpleAssignmentAnalyzer.<>c.<Initialize>b__3_0(SyntaxNodeAnalysisContext c)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__53`1.<ExecuteSyntaxNodeAction>b__53_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.
```
